name: Bakery

on:
  push:
    branches: [main]

jobs:
  mochi:
    runs-on: ubuntu-latest
    steps:
      - name: "dubai mochi"
        run: echo "두바이 모찌빵"

      - name: "sweet potato mochi"
        run: echo "고구마 모찌빵"

      - name: "egg tart"
        run: echo "에그 타르트"

  gelato:
    runs-on: ubuntu-latest
    steps:
      - name: "milk gelato"
        run: echo "우유 젤라또"

      - name: "chocolate gelato"
        run: echo "초콜릿 젤라또"

      - name: "mint choco gelato"
        run: echo "민트 초코 젤라또"
